/**
 * scripts/download-images.ts
 * 
 * Downloads every item image from the authoritative hamsa_menu.json source
 * into /public/img/menu/[slug].jpg (self-hosted).
 * 
 * Also generates:
 *  - supabase/migrations/004_fix_image_urls.sql  — UPDATE statements to point items
 *    to the correct local /img/menu/[slug].jpg path (matched by name).
 *  - scripts/verify-images.ts output               — run separately after.
 *
 * Usage:  npx tsx scripts/download-images.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { resolve } from "path";
import https from "https";
import http from "http";
import fs from "fs";

dotenv.config({ path: resolve(process.cwd(), ".env.local") });

// ─── helpers ─────────────────────────────────────────────────────────────────

/** kebab-case slug, strips accents, lowercases, collapses spaces */
function slugify(name: string): string {
  return name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")   // strip accents
    .toLowerCase()
    .replace(/['']/g, "")              // remove apostrophes
    .replace(/[^a-z0-9]+/g, "-")      // non-alphanumeric → dash
    .replace(/^-+|-+$/g, "");         // trim leading/trailing dashes
}

/** Download a URL to a local file path. Returns true on success. */
function downloadFile(url: string, dest: string): Promise<boolean> {
  return new Promise((resolve) => {
    const file = fs.createWriteStream(dest);
    const protocol = url.startsWith("https") ? https : http;

    const req = protocol.get(url, { timeout: 15_000 }, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        // follow one redirect
        file.close();
        if (res.headers.location) {
          downloadFile(res.headers.location, dest).then(resolve);
        } else {
          resolve(false);
        }
        return;
      }
      if (!res.statusCode || res.statusCode >= 400) {
        file.close();
        resolve(false);
        return;
      }
      res.pipe(file);
      file.on("finish", () => { file.close(); resolve(true); });
    });

    req.on("error", () => { file.close(); resolve(false); });
    req.on("timeout", () => { req.destroy(); file.close(); resolve(false); });
  });
}

// ─── main ────────────────────────────────────────────────────────────────────

async function main() {
  const menuPath = resolve(process.cwd(), "hamsa_menu.json");
  const menuData = JSON.parse(readFileSync(menuPath, "utf-8"));

  const outDir = resolve(process.cwd(), "public/img/menu");
  mkdirSync(outDir, { recursive: true });
  console.log(`\n📁  Output directory: ${outDir}\n`);

  // ── connect to Supabase to get current item IDs ───────────────────────────
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
  const supabase = createClient(url, key);
  const { data: dbItems, error } = await supabase
    .from("items")
    .select("id, name, image_url");

  if (error) {
    console.error("❌  Could not fetch items from Supabase:", error.message);
    console.log("Continuing to generate SQL without DB verification...\n");
  }

  const dbMap = new Map<string, { id: string; image_url: string | null }>();
  for (const row of dbItems ?? []) {
    dbMap.set(slugify(row.name), { id: row.id, image_url: row.image_url });
  }

  // ── process every item from the JSON ─────────────────────────────────────
  const sqlLines: string[] = [
    "-- 004_fix_image_urls.sql",
    "-- Auto-generated by scripts/download-images.ts",
    "-- Each UPDATE matches by item name (case-insensitive) and sets the correct",
    "-- self-hosted /img/menu/<slug>.jpg path (or NULL for items with no photo).",
    "",
  ];

  const report: string[] = [
    "| Category | Item Name | Image Source | Local Path | Status |",
    "|----------|-----------|--------------|------------|--------|",
  ];

  let downloaded = 0, skipped = 0, noPhoto = 0, failed = 0;

  for (const cat of menuData.categories) {
    for (const item of cat.items) {
      const slug = slugify(item.name);
      const localPath = `/img/menu/${slug}.jpg`;
      const destFile = resolve(outDir, `${slug}.jpg`);
      const imgUrl: string | null = item.image;

      if (!imgUrl) {
        // No photo in source data
        noPhoto++;
        // TODO: needs photo — shop should supply an image for this item
        sqlLines.push(
          `-- TODO: needs photo\n` +
          `UPDATE items SET image_url = NULL WHERE lower(name) = lower('${item.name.replace(/'/g, "''")}');`
        );
        report.push(
          `| ${cat.name} | ${item.name} | *(none)* | NULL | ⚠️ no photo |`
        );
        continue;
      }

      // Download if not already present
      if (existsSync(destFile)) {
        console.log(`  ✓ already exists  ${slug}.jpg`);
        skipped++;
      } else {
        console.log(`  ⬇  downloading    ${slug}.jpg  ← ${imgUrl}`);
        const ok = await downloadFile(imgUrl, destFile);
        if (ok) {
          downloaded++;
          console.log(`     saved ✓`);
        } else {
          failed++;
          console.log(`     FAILED ✗ — will keep tablebeep URL as fallback`);
          // fall back to the direct URL so the item still shows something
          sqlLines.push(
            `UPDATE items SET image_url = '${imgUrl}' WHERE lower(name) = lower('${item.name.replace(/'/g, "''")}');`
          );
          report.push(
            `| ${cat.name} | ${item.name} | ${imgUrl} | (fallback URL) | ❌ download failed |`
          );
          continue;
        }
      }

      // Correct local path
      sqlLines.push(
        `UPDATE items SET image_url = '${localPath}' WHERE lower(name) = lower('${item.name.replace(/'/g, "''")}');`
      );
      report.push(
        `| ${cat.name} | ${item.name} | ${imgUrl} | ${localPath} | ✅ |`
      );
    }
  }

  // ── write SQL ──────────────────────────────────────────────────────────────
  const sqlPath = resolve(process.cwd(), "supabase/migrations/004_fix_image_urls.sql");
  writeFileSync(sqlPath, sqlLines.join("\n"), "utf-8");
  console.log(`\n📝  SQL written → ${sqlPath}`);

  // ── write report ───────────────────────────────────────────────────────────
  const reportPath = resolve(process.cwd(), "scripts/image-report.md");
  writeFileSync(reportPath, `# Image Mapping Report\n\n${report.join("\n")}\n\n` +
    `## Summary\n- ✅ Downloaded: ${downloaded}\n- ⏭  Already existed: ${skipped}\n` +
    `- ⚠️  No photo in source: ${noPhoto}\n- ❌ Failed: ${failed}\n`, "utf-8");
  console.log(`📊  Report written → ${reportPath}`);

  console.log(`\n✅  Done!  downloaded=${downloaded}  skipped=${skipped}  noPhoto=${noPhoto}  failed=${failed}`);
  console.log(`\nNext step: run the generated SQL in Supabase SQL Editor:`);
  console.log(`  supabase/migrations/004_fix_image_urls.sql\n`);
}

main().catch(console.error);
