-- 004_fix_image_urls.sql
-- Auto-generated by scripts/download-images.ts
-- Each UPDATE matches by item name (case-insensitive) and sets the correct
-- self-hosted /img/menu/<slug>.jpg path (or NULL for items with no photo).

UPDATE items SET image_url = '/img/menu/bruschetta-caprese.jpg' WHERE lower(name) = lower('Bruschetta Caprese');
UPDATE items SET image_url = '/img/menu/bruschetta-avocat-saumon.jpg' WHERE lower(name) = lower('Bruschetta Avocat Saumon');
UPDATE items SET image_url = '/img/menu/bruschetta-avocat-crevettes.jpg' WHERE lower(name) = lower('Bruschetta Avocat Crevettes');
UPDATE items SET image_url = '/img/menu/bruschetta-burrata.jpg' WHERE lower(name) = lower('Bruschetta Burrata');
UPDATE items SET image_url = '/img/menu/brioche-forestiere.jpg' WHERE lower(name) = lower('Brioche Forestière');
UPDATE items SET image_url = '/img/menu/brioche-harmonie.jpg' WHERE lower(name) = lower('Brioche Harmonie');
UPDATE items SET image_url = '/img/menu/hamsa-moment.jpg' WHERE lower(name) = lower('Hamsa Moment');
UPDATE items SET image_url = '/img/menu/tuna-club-sandwich.jpg' WHERE lower(name) = lower('Tuna Club Sandwich');
UPDATE items SET image_url = '/img/menu/chicken-club-sandwich.jpg' WHERE lower(name) = lower('Chicken Club Sandwich');
UPDATE items SET image_url = '/img/menu/croissant-sale.jpg' WHERE lower(name) = lower('Croissant Salé');
UPDATE items SET image_url = '/img/menu/burrata-fraiche.jpg' WHERE lower(name) = lower('Burrata Fraîche');
UPDATE items SET image_url = '/img/menu/burrata-sweet.jpg' WHERE lower(name) = lower('Burrata Sweet');
UPDATE items SET image_url = '/img/menu/hamsa-soleil.jpg' WHERE lower(name) = lower('Hamsa Soleil');
UPDATE items SET image_url = '/img/menu/brioche-tiramisu.jpg' WHERE lower(name) = lower('Brioche Tiramisu');
UPDATE items SET image_url = '/img/menu/brioche-dor.jpg' WHERE lower(name) = lower('Brioche D''or');
UPDATE items SET image_url = '/img/menu/pancakes-sirop-derable.jpg' WHERE lower(name) = lower('Pancakes Sirop D''érable');
UPDATE items SET image_url = '/img/menu/pancakes-gourmands.jpg' WHERE lower(name) = lower('Pancakes Gourmands');
UPDATE items SET image_url = '/img/menu/waffle-caramel.jpg' WHERE lower(name) = lower('Waffle Caramel');
UPDATE items SET image_url = '/img/menu/waffle-chocolat.jpg' WHERE lower(name) = lower('Waffle Chocolat');
UPDATE items SET image_url = '/img/menu/waffle-pistache.jpg' WHERE lower(name) = lower('Waffle Pistache');
UPDATE items SET image_url = '/img/menu/crepe-gourmande.jpg' WHERE lower(name) = lower('Crêpe gourmande');
UPDATE items SET image_url = '/img/menu/pavlova-aux-fruits-rouges.jpg' WHERE lower(name) = lower('Pavlova Aux Fruits Rouges');
UPDATE items SET image_url = '/img/menu/pavlova-mangue.jpg' WHERE lower(name) = lower('Pavlova Mangue');
UPDATE items SET image_url = '/img/menu/granola-bowl.jpg' WHERE lower(name) = lower('Granola Bowl');
UPDATE items SET image_url = '/img/menu/crumble-aux-pomme.jpg' WHERE lower(name) = lower('Crumble Aux Pomme');
UPDATE items SET image_url = '/img/menu/jardin-de-sicile.jpg' WHERE lower(name) = lower('Jardin De Sicile');
UPDATE items SET image_url = '/img/menu/boule-de-glace.jpg' WHERE lower(name) = lower('Boule De Glace');
UPDATE items SET image_url = '/img/menu/espresso.jpg' WHERE lower(name) = lower('Espresso');
UPDATE items SET image_url = '/img/menu/double-espresso.jpg' WHERE lower(name) = lower('Double Espresso');
UPDATE items SET image_url = '/img/menu/cafe-capsule.jpg' WHERE lower(name) = lower('Cafe Capsule');
UPDATE items SET image_url = '/img/menu/cortado.jpg' WHERE lower(name) = lower('Cortado');
UPDATE items SET image_url = '/img/menu/cappuccino.jpg' WHERE lower(name) = lower('Cappuccino');
UPDATE items SET image_url = '/img/menu/cappuccino-personnalisee-photo.jpg' WHERE lower(name) = lower('Cappuccino personnalisée photo');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Cappuccino Brûlée');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Mocaccino');
UPDATE items SET image_url = '/img/menu/latte-macchiato-vanille-caramel-noisette.jpg' WHERE lower(name) = lower('Latte Macchiato (vanille-caramel-noisette)');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('The Infusion');
UPDATE items SET image_url = '/img/menu/chocolat-chaud.jpg' WHERE lower(name) = lower('Chocolat Chaud');
UPDATE items SET image_url = '/img/menu/hot-milk.jpg' WHERE lower(name) = lower('Hot Milk');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Americano');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Matcha Latte');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Caramel Latte');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Vanilla Latte');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Pistachio Latte');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Spanish Latte');
UPDATE items SET image_url = '/img/menu/iced-americano.jpg' WHERE lower(name) = lower('Iced Americano');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Iced Spanish Latte');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Iced Caramel Latte');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Iced Speculos Latte');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Iced Vanilla Latte');
UPDATE items SET image_url = '/img/menu/iced-tiramisu-latte.jpg' WHERE lower(name) = lower('Iced Tiramisu Latte');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Iced Coconut Latte');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Iced Pistachio Latte');
UPDATE items SET image_url = '/img/menu/iced-matcha-latte.jpg' WHERE lower(name) = lower('Iced Matcha Latte');
UPDATE items SET image_url = '/img/menu/iced-strawberry-matcha.jpg' WHERE lower(name) = lower('Iced Strawberry Matcha');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Mango Matcha');
UPDATE items SET image_url = '/img/menu/iced-ube-latte.jpg' WHERE lower(name) = lower('Iced Ube Latte');
UPDATE items SET image_url = '/img/menu/iced-ube-caramel.jpg' WHERE lower(name) = lower('Iced Ube Caramel');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Iced Ube Vanille');
UPDATE items SET image_url = '/img/menu/iced-ube-pistachio.jpg' WHERE lower(name) = lower('Iced Ube Pistachio');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Frappuccino Caramel');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Frappuccino Choco');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Frappuccino Cookies');
UPDATE items SET image_url = '/img/menu/milkshake-banane-speculoos.jpg' WHERE lower(name) = lower('Milkshake Banane-Spéculoos');
UPDATE items SET image_url = '/img/menu/milkshake-fruits-rouges.jpg' WHERE lower(name) = lower('Milkshake Fruits Rouges');
UPDATE items SET image_url = '/img/menu/milkshake-crumble-cookies.jpg' WHERE lower(name) = lower('Milkshake Crumble Cookies');
UPDATE items SET image_url = '/img/menu/milkshake-mangue.jpg' WHERE lower(name) = lower('Milkshake Mangue');
UPDATE items SET image_url = '/img/menu/mojito-classique.jpg' WHERE lower(name) = lower('Mojito Classique');
UPDATE items SET image_url = '/img/menu/mojito-fruits-rouges.jpg' WHERE lower(name) = lower('Mojito Fruits Rouges');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Yuzu Fizz');
UPDATE items SET image_url = '/img/menu/smoothie-banane.jpg' WHERE lower(name) = lower('Smoothie Banane');
UPDATE items SET image_url = '/img/menu/smoothie-fraise.jpg' WHERE lower(name) = lower('Smoothie Fraise');
UPDATE items SET image_url = '/img/menu/jus-dorange.jpg' WHERE lower(name) = lower('Jus D''Orange');
UPDATE items SET image_url = '/img/menu/citronade.jpg' WHERE lower(name) = lower('Citronade');
UPDATE items SET image_url = '/img/menu/jus-de-fruit-de-saison.jpg' WHERE lower(name) = lower('Jus De Fruit De Saison');
UPDATE items SET image_url = '/img/menu/pinacolada.jpg' WHERE lower(name) = lower('Pinacolada');
UPDATE items SET image_url = '/img/menu/blush.jpg' WHERE lower(name) = lower('Blush');
UPDATE items SET image_url = '/img/menu/ocean-wave.jpg' WHERE lower(name) = lower('Ocean Wave');
-- TODO: needs photo
UPDATE items SET image_url = NULL WHERE lower(name) = lower('Eau');